Create PrincessGame
vsoilol/MainRepository_SokolovVlad pull request #2
Opened 2020-11-27 16:04 UTC by vsoilol

2020-11-27 16:05 UTC, vsoilol commented
![](https://github.trello.services/images/mini-trello-icon.png) [[TMM-26] Princess Game](https://trello.com/c/YZNVNGbt/58-tmm-26-princess-game)

2020-11-29 09:49 UTC, AnastasiaKorotkevich reviewed
Для начала переделай хотя бы по конвенции. Код очень грязный.

2020-11-29 09:49 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/DateTimeCompare.cs
> +    }
Для чего это? К тому же не соблюдена конвенция.

2020-11-29 09:49 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        private int _numberTraps = 0;
Слишком грязный код.

2020-12-02 00:49 UTC, BitW13 reviewed
Вроде норм, пересмотри ещё раз, есть косметические проблемы
А так с абстракцией всё ок

2020-12-02 00:49 UTC, BitW13 commented on EPAMHomework_SokolovVlad/DateTimeCompare.cs
> +    public class DateTimeCompare : IComparer<HallOfFameEntry>
DateTimeComparer

2020-12-02 00:49 UTC, BitW13 commented on EPAMHomework_SokolovVlad/Game.cs
> +        private DateTime passageTime;
Добавь отступ

2020-12-02 00:49 UTC, BitW13 commented on EPAMHomework_SokolovVlad/Game.cs
> +            borderSizeX = fieldSizeX + 2;
Что такое 2? нужен const

2020-12-02 00:49 UTC, BitW13 commented on EPAMHomework_SokolovVlad/Game.cs
> +        }
Нужен отступ

2020-12-02 00:49 UTC, BitW13 commented on EPAMHomework_SokolovVlad/Game.cs
> +        }
После методов - отступ

2020-12-02 00:55 UTC, AnastasiaKorotkevich requested changes

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/ConsoleOutput.cs
> +        public static string EnterRecord()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/ConsoleOutput.cs
> +        public static void LoseGame()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/ConsoleOutput.cs
> +        public static void WinGame()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public Game(int fieldSizeX, int fieldSizeY, int numberTraps)
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void AddTime(object state)
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void PlayGame()//играть
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void CreateTraps()//Создать ловушки
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void ShowTraps()//Показать или скрыть ловушки
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void CreateHPMenu()//Счетчик HP
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void CreateField()//Создать рамку
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void CreatePlayer()//Создать игрока
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void CreatePrincess()//Создать принцессу
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void MovePlayer(Move move)//Передвинуть игрока
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void EncounteredTrap()//Встречаются Ловушки
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void ShowCausedDamage(int damage)//Показывает какой урон получил
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void StartNewGame()//Начать новую игру
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void RunMenu()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void ResetGame()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void WriteRecord()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Game.cs
> +        public void FoundPrincess()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/HallOfFame.cs
> +        public static void AddResult(HallOfFameEntry entry)
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/HallOfFame.cs
> +        private static void SaveHallOfFame()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/HallOfFame.cs
> +        public static void ShowHallOfFame()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Player.cs
> +        public Player(int borderX, int borderY)
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Player.cs
> +        public bool DepriveHealth(int damage)
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Player.cs
> +        public int GetPositionX()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Player.cs
> +        public int GetPositionY()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Player.cs
> +        public void DrawPlayer()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Player.cs
> +        public void MovePlayer()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Player.cs
> +        public bool LeaveBorder()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Player.cs
> +        public bool FoundPrincess(Point princess)
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Player.cs
> +            return false;
Здесь лучше тернарный оператор.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Trap.cs
> +        public Trap(int maxHealth, int maxPositionY, int maxPositionX, int positionPlayerX, int positionPlayerY, int positionPrincessX, int positionPrincessY)
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Trap.cs
> +        public bool FallTrap(int positionX, int positionY)
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Trap.cs
> +        public void HideTrap()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Trap.cs
> +        public void ViewTrap()
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Сoordinate.cs
> +        public void DrawPoint(char drawing)
Отступ.

2020-12-02 00:55 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Сoordinate.cs
> +        public void ClearPoint()
Отступ.

2020-12-02 13:25 UTC, BitW13 approved these changes
Мержи

2020-12-02 17:25 UTC, merged