BankGame
vsoilol/MainRepository_SokolovVlad pull request #4
Opened 2020-12-08 19:37 UTC by vsoilol

2020-12-08 19:38 UTC, vsoilol commented
![](https://github.trello.services/images/mini-trello-icon.png) [[TMM-31] Bank](https://trello.com/c/cAnluaJG/65-tmm-31-bank)

2020-12-13 23:34 UTC, AnastasiaKorotkevich reviewed
Есть проблемы с именами методов в некоторых местах. Пересмотри. И можно сделать немного лучше в плане абстракции между картой и счетом, все-таки правильнее будет класть деньги на счет, а не на карту.

2020-12-13 23:34 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Account.cs
> +            const string dictionaryString = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
Это лучше вынести к остальным константам.

2020-12-13 23:34 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +        public void PutMoneyCard()
```suggestion
        public void PutMoneyToCard()
```

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Account.cs
> +            if ((Money - amountMoney) < 0)
Проверку можно упростить. Почему бы не сравнить значения остатка и суммы для снятия?

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Account.cs
> +        public bool WithdrawMoneyFromAccount(double amountMoney)
Название не по конвенции, если метод bool.

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/AccountType.cs
> +        Deposit,
По конвенции дефолтные значения проставляются везде, в том числе и ",".

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
>              return false;
Немного странная логика. Тут можно и из foreach уже вернуть false, если встретился в инетерации счет без карты, тк именно об этом и говорит название метода.
Почему бы не сделать в теле цикла тернарный оператор?

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +            ConsoleProvider.ChooseCard("Выберете счет и карту с которой будет производится перевод.");
В константы.

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +            }
Тут можно сократить до тернарного вроде как.

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +            ConsoleProvider.ChooseCard("Выберете счет на который будет сделан перевод.");
В константы.

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
>              int transferableMoney = ConsoleProvider.EnterMoney("Введите сумму для перевода: ");
В константы.

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +            ConsoleProvider.ChooseCard("Выберете счет с которого будет производится перевод.");
В константы.

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
>          public void TransferToAccount()
Transfer чего?

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
>              int transferableMoney = ConsoleProvider.EnterMoney("Введите сумму для перевода: ");
В константы.

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Card.cs
> +        public virtual bool TransferToCard(Account account, Account transferableAccount, int amountMoney)
То же самое с названием.

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/ConsoleProvider.cs
>          private const string whatDo = "Что вы хотите сделать?";
Названия не по конвенции.

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/ConsoleProvider.cs
> +                    Console.WriteLine($"{i}. {accounts[i - 1].NameAccount} - депозитный счет");
Строки в константы.

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/ConsoleProvider.cs
> +        }
Этот метод больше относится к Account.

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/ConsoleProvider.cs
> +        public static void ShowNameCard(string name, CardType cardType)
Этот метод больше относится к Card.

2020-12-16 01:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/CreditCard.cs
> +        private readonly double monthlyDebt;
Нет смысла делать разделения на кредитную карту и дебетовую здесь. Все операции, зависящие от этого, совершаются со счетом. Для карты достаточно привязки, генерации номера и пр.

2020-12-16 06:37 UTC, vsoilol commented on EPAMHomework_SokolovVlad/Bank.cs
> +            }
Там пишет что "Функция "условное выражение с целевым типом" недоступна"

2020-12-16 06:38 UTC, vsoilol commented on EPAMHomework_SokolovVlad/Bank.cs
>              return false;
Здесь я проверяю все счета на наличие карты, и если ни на одном счете его нет то возвращается false

2020-12-17 00:46 UTC, AnastasiaKorotkevich reviewed
Нужно вынести соотвутствующий функционал из Bank в Debit Account и Credit Account.

2020-12-17 00:46 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +        private const string withdrawMoneyFromAccount = "Введите сумму которую хотите снять со счета: ";
Константы называются всегда через PascalCase.

2020-12-17 00:46 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +            }
Это лучше вынести в Account.

2020-12-17 00:46 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +                    foreach (Credit credit in (account as CreditAccount).Credits)
Это лучше вынести в Account.

2020-12-17 00:46 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +            Credit credit;
Это лучше вынести в Account.

2020-12-17 00:46 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +            Account account = ShowListAccounts(true);
Это лучше вынести в Account.

2020-12-17 00:46 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +            Account account = ShowListAccounts(true);
Это лучше вынести в Account.

2020-12-17 00:46 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +        public bool AreHaveCards()
Это лучше вынести в Account.

2020-12-17 00:46 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +        public bool AreHaveCards()
```suggestion
        public bool AreAccountHaveCards()
```

2020-12-17 00:46 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +        public void AddCreditToAccount()
Это лучше вынести в Account.

2020-12-17 12:42 UTC, AnastasiaKorotkevich requested changes

2020-12-17 12:42 UTC, AnastasiaKorotkevich commented on EPAMHomework_SokolovVlad/Bank.cs
> +                account = ChooseAccount(true);
Этот метод ведь уже есть в Credit

2020-12-17 13:22 UTC, vsoilol commented on EPAMHomework_SokolovVlad/Bank.cs
> +                account = ChooseAccount(true);
В классе Bank он выбирает счет и проверят не выбран ли DepositAccount, если выбран то выводится сообщение об ошибке, а если выбран CreditAccount запускается метод RepayDept у CreditAccount

2020-12-17 22:13 UTC, BitW13 reviewed
Задачи должны быть в одном репозитории
При втором задании не нужно удалять первое
Нужно создать отдельные папки под задачи
Это оговаривалось ещё в начале

2020-12-19 23:30 UTC, BitW13 reviewed
и т.д. и т.д.
Пересмотри всё

2020-12-19 23:30 UTC, BitW13 commented on BankGame/Account.cs
> +﻿using System;
![image](https://user-images.githubusercontent.com/28789651/102701692-9fce5c00-426a-11eb-8fe2-d655813df400.png)
Я взял 100, прошло 2 месяца...
Чего так много????
И почему меня в консоли не уведомили о проценте кредита??

2020-12-19 23:30 UTC, BitW13 commented on BankGame/Account.cs
> +        private const string DictionaryString = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
Зачем эти данные?
Как я понял, можно было бы просто заюзать количество символов

2020-12-19 23:30 UTC, BitW13 commented on BankGame/Bank.cs
> +        public void AddCreditToAccount()
А это разве не должно быть в классе Account?

2020-12-19 23:30 UTC, BitW13 commented on BankGame/Bank.cs
> +        public bool AreAccountsHaveCards()
А это разве не должно быть в классе Account?

2020-12-19 23:30 UTC, BitW13 commented on BankGame/Bank.cs
> +        public void AddCardToAccount()
А это разве не должно быть в классе Account?

2020-12-19 23:30 UTC, BitW13 commented on BankGame/Bank.cs
> +        public void PutMoneyToAccount()
А это разве не должно быть в классе Account?

2020-12-19 23:30 UTC, BitW13 commented on BankGame/Bank.cs
> +        public void WithdrawMoneyFromAccount()
А это разве не должно быть в классе Account?

2020-12-19 23:30 UTC, BitW13 commented on BankGame/Bank.cs
> +        public void TransferFromAccountToCard()
Что за хрень?

2020-12-20 09:07 UTC, vsoilol commented on BankGame/Account.cs
> +        private const string DictionaryString = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
DictionaryString нужно для того, что бы сгенерировать номер счета

2020-12-20 09:32 UTC, vsoilol commented on BankGame/Bank.cs
> +        public bool AreAccountsHaveCards()
Здесь я проверяю все счета на наличие карты, и если ни на одном счете его нет то возвращается false

2020-12-20 22:37 UTC, BitW13 approved these changes
Если всё же та переменная нужно, то ладно
Мерж
Абстракция норм

2020-12-20 22:37 UTC, BitW13 commented on BankGame/Account.cs
> +        private const string DictionaryString = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";
Так ты ведь юзаешь только DictionaryString.Length, разве нет?

2020-12-21 07:05 UTC, merged